version: '3.8'

services:
  postgres:
    container_name: research_engine_bdd
    image: postgres:16.1-alpine
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "admin" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: unless-stopped
    env_file: 
      - docker.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_rs_engine_data:/var/lib/postgresql/data

  pgadmin:
    container_name: research_engine_pgadmin
    image: dpage/pgadmin4
    restart: unless-stopped
    env_file: 
      - docker.env
    ports:
      - "8080:80"
    volumes:
      - pgadmin_rs_engine_data:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  postgres_rs_engine_data:
  pgadmin_rs_engine_data:

